### ISSUE TITLE
实验设备问题

### ISSUE THREAD

**Issue by dy-ux** [1053399472/CAISandSMP#1]
您好，请问您的结果是在什么GPU设备以及pytorch版本上跑出来的呢？能方便告知一下吗？

**Comment by 1053399472** [comment]
GeForce RTX 3080 Tipytorch 版本v1.11.0

**Comment by 1053399472** [comment]
GeForce RTX 3080 Ti           
pytorch v1.11.0

**Comment by dy-ux** [comment]
好的，谢谢。请问后续会发布源码吗？

**Comment by 1053399472** [comment]
The detailed code of our paper will be uploaded soon

**Comment by dy-ux** [comment]
ok.thanks
