### ISSUE TITLE
About MLWA+RoBERTa's reproduction problem

### ISSUE THREAD

**Issue by dy-ux** [1053399472/CAISandSMP#3]
There is an error in the evaluation procedure in the MLWA source code, have you made any changes to this? Regarding the MLWA+RoBERTa results, did you run the source code directly based on the parameters provided in the source code to get the results?
MLWA源代码的评估程序有错误，请问您对此进行修改了吗？关于MLWA+RoBERTa的结果，您是根据源码提供的参数直接运行源码得出的结果吗？

**Comment by 1053399472** [comment]
For the questions in the MLWA source code, please read the following warehouse https://github.com/1053399472/MLWA-Chinese-SLU-baseline. With regard to the results of MLWA+RoBERTa, the parameters of the original author have not been modified, but the pre-training model hfl/chinese-roberta-wwm-ext, which is consistent with our model, is adopted.

**Comment by dy-ux** [comment]
thanks
